name: Build Publish Release

on:
  workflow_dispatch:
  schedule:
    - cron: "0 20 1,15 * *"

jobs:
  build:
    uses: ./.github/workflows/action_build.yml

  publish:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      # 构建发布所需的环境
      - uses: pnpm/action-setup@v4
        with:
          version: "^10.21.0"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=23.7.0"

      - run: pnpm init
      - run: pnpm i -D publish-browser-extension

      # 下载 action_build.yml 构造出来的 extension-chrome.zip, extension-firefox.zip 两个文件
      - name: Download Chrome Built Artifact
        uses: actions/download-artifact@v4
        with:
          pattern: build-zip-*
          merge-multiple: true

      # 发布 GitHub Release
      - id: github_release
        uses: ncipollo/release-action@v1
        with:
          name: v${{ needs.build.outputs.version }}
          tag: v${{ needs.build.outputs.version }}
          skipIfReleaseExists: true
          generateReleaseNotes: true
          artifacts: "extension-chrome.zip,extension-firefox.zip"

      # 提交至 Store
      - name: Publish to Chrome Web Store
        if: ${{ steps.github_release.outputs.id != '' }}
        continue-on-error: true
        env:
          CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
          CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
          CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
          CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
          CHROME_PUBLISH_TARGET: ${{ secrets.CHROME_PUBLISH_TARGET }}
          CHROME_SKIP_SUBMIT_REVIEW: ${{ secrets.CHROME_SKIP_SUBMIT_REVIEW }}
        run: pnpm exec publish-extension --chrome-zip extension-chrome.zip

      ## 下载用于 firefox 商店提交的源代码
      ## 由于 workflow_dispatch 和 schedule 触发的工作流其 GITHUB_SHA 永远为最新提交的 SHA，此处可以直接固定死下载最新的源代码
      - run: wget https://github.com/pt-plugins/PT-depiler/archive/refs/heads/master.zip -O source.zip

      - name: Publish to Firefox Add-ons
        if: ${{ steps.github_release.outputs.id != '' }}
        continue-on-error: true
        env:
          FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
          FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
          FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
          FIREFOX_CHANNEL: ${{ secrets.FIREFOX_CHANNEL }}
        run: pnpm exec publish-extension --firefox-zip extension-firefox.zip --firefox-sources-zip source.zip

      - name: Publish to Microsoft Edge Add-ons
        if: ${{ steps.github_release.outputs.id != '' }}
        continue-on-error: true
        env:
          EDGE_PRODUCT_ID: ${{ secrets.EDGE_PRODUCT_ID }}
          EDGE_CLIENT_ID: ${{ secrets.EDGE_CLIENT_ID }}
          EDGE_API_KEY: ${{ secrets.EDGE_API_KEY }}
          EDGE_SKIP_SUBMIT_REVIEW: ${{ secrets.EDGE_SKIP_SUBMIT_REVIEW }}
        run: pnpm exec publish-extension --edge-zip extension-chrome.zip
