# 这是一个临时性用来构建测试包的action

name: Build Action Release

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ">=23.7.0"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: vue-tsc check
        run: pnpm check
        continue-on-error: true

      - name: Build Output
        run: |
          pnpm build:dist
          pnpm build:dist-firefox

      - name: Upload Chrome Built to action
        uses: actions/upload-artifact@v4
        with:
          name: build-dist-chrome
          path: dist-chrome

      - name: Upload Firefox Built to action
        uses: actions/upload-artifact@v4
        with:
          name: build-dist-firefox
          path: dist-firefox

      - run: mkdir -p build-zip

      - id: zip_chrome
        name: Build Zip For Chrome
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "dist-chrome"
          zipFilePath: "build/extension-chrome.zip"

      - id: zip_firefox
        name: Build Zip For Firefox
        uses: cardinalby/webext-buildtools-pack-extension-dir-action@v1
        with:
          extensionDir: "dist-firefox"
          zipFilePath: "build/extension-firefox.zip"

      - name: Upload Built Zip to action
        uses: actions/upload-artifact@v4
        with:
          name: build-zip-${{ steps.zip_chrome.outputs.extensionVersion }}
          path: build/*.zip

      - name: Upload build Zip to Telegram Channel
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' && env.TELEGRAM_BOT_TOKEN != '' && env.TELEGRAM_CHAT_ID != '' }}
        run: pnpm telegram:upload
        continue-on-error: true
